@url = http://10.3.3.34:5000

GET {{url}}/ambiente?idAmbiente=0 HTTP/1.1

###

GET {{url}}/sumMonth?nomeAmbiente=TUDOTUDO HTTP/1.1

###

# POST {{url}}/abientes HTTP/1.1
# Content-Type: application/json

# {
#     "":""
# }
